apiVersion: v1
kind: Pod
metadata:
  name: logrotate
  namespace: kube-system
  labels:
    k8s-ilke: logrotate
spec:
  dnsPolicy: Default
  containers:
  - image: mumoshu/kube-logrotate:0.1.0
    name: logrotate
    
    
    env:
    - name: LOGROTATE_ARGS
      value: -v

    volumeMounts:
    - name: varlog
      mountPath: /var/log/containers
    - name: varlog1
      mountPath: /var/log/kubernetes

  volumes:
    - name: varlog
      hostPath: 
        path: /var/log/containers
        type: Directory
    - name: varlog1
      hostPath: 
        path: /var/log/kubernetes
        type: Directory
    - name: logrotate-conf
      configMap:
        name: logrotate-config

   
     