apiVersion: v1
kind: Pod
metadata:
  name: logrotate
  namespace: kube-system
  labels:
    k8s-ilke: logrotate
spec:
  dnsPolicy: Default
  containers:
  - name: logrotate
    image: mumoshu/kube-logrotate:0.1.0
        
    env:
    - name: LOGROTATE_ARGS
      value: -v
   # volumeMounts:
   # - name: varlog
    #  mountPath: /var/log/containers
    #- name: varlog1
     # mountPath: /var/log/kubernetes
   
     